---
title: "Exercises"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

<style> p { text-align: justify; } </style>

At the end of this tutorial, you should have a solid understanding of key geospatial operations in R, from handling vector and raster data to performing advanced spatial analyses. To ensure that you've mastered the concepts and are able to apply the techniques covered, let's test your skills with the following practical exercises. These tasks will help you reinforce your understanding of spatial data manipulation, analysis, and visualization:

**1. Subset the Kanchanpur district polygon** and extract the region named "Mahendranagar". Plot the subsetted region to visualize it.

**2. Compute the area of the Mahendranagar region** in square kilometers and explore its geographic size.

**3. Calculate the perimeter of the Mahendranagar region**, another key geometric property that provides insights into the shape of the region.

**4. Analyze the change in population** in the Mahendranagar region from the year 2000 to 2020 using zonal statistics and raster data. This will help you understand how to use raster data to compute statistical summaries over specific geographic areas.

**5. Create a custom function ** that takes polygon and raster data, masks the raster to the polygon's boundary, converts the masked raster to a data frame with coordinate columns, and returns a preview of the data frame.

**6. Create a geospatial data frame** consisting of five points (A, B, C, D, and E), and add a new column representing temperature values in Celsius.

**7. Load ESA Land Cover data** for 2015 and 2019, compute and visualize the change raster for the Mahendranagar region, and check the summary statistics to assess the changes in land cover over time.

**8. Create a function named `get_popCount()`** that takes the ISO3 country code and year as arguments, and downloads the Population Count Raster from the WorldPop Hub. Click here for the [source URL](https://hub.worldpop.org/geodata/listing?id=69).

These exercises will provide you with hands-on practice in performing common geospatial operations in R, ensuring you're well-prepared to handle spatial datasets and solve real-world geographic problems using R and its geospatial packages.

**If you have any questions or encounter any difficulties while solving these exercises, feel free to visit my [GitHub page](https://github.com/Ohm-Np/R_tutorial) and open an issue.**
